taxonomy_section_paths.settings:
  type: config_object
  label: 'Taxonomy Section Paths settings'
  mapping:
    bundles:
      type: mapping
      label: 'Bundles configuration'
      mapping:
        '*':
          type: mapping
          label: 'Bundle settings'
          mapping:
            vocabulary:
              type: string
              label: 'Vocabulary'
            field:
              type: string
              label: 'Reference field'
    generate_node_alias_if_term_empty:
      type: boolean
      label: 'Generate alias if term empty'
    enable_event_logging:
      type: boolean
      label: 'Enable event logging'
    silent_messages:
      type: boolean
      label: 'Silent messages'
    use_batch_for_term_operations:
      type: boolean
      label: 'Use batch for term operations'
